### ISSUE TITLE
TODO: automate importing spreadsheet into online database

### ISSUE THREAD

**Issue by GloriousEggroll** [Open-Wine-Components/ULWGL-database#4]
- basically we need to create a script that pulls the data from the spreadsheet and parses it into sql entries -- then adds those entries to an sql database. this script should be run as a daily cronjob
 ̶-̶ ̶s̶w̶i̶t̶c̶h̶ ̶s̶p̶r̶e̶a̶d̶s̶h̶e̶e̶t̶ ̶t̶o̶ ̶p̶l̶a̶i̶n̶ ̶t̶e̶x̶t̶ ̶c̶s̶v̶ ̶f̶o̶r̶m̶a̶t̶ ̶s̶o̶ ̶t̶h̶a̶t̶ ̶i̶t̶'̶s̶ ̶e̶a̶s̶i̶l̶y̶ ̶r̶e̶a̶d̶a̶b̶l̶e̶ ̶o̶n̶ ̶g̶i̶t̶h̶u̶b̶ done https://github.com/Open-Wine-Components/ULWGL-database/commit/a68d7f5da434433dd1e480b826efb8ab0fc06bbc

**Comment by strycore** [comment]
Shouldn't we stop using a spreadsheet once we have an API in place?

**Comment by GloriousEggroll** [comment]
discussed on discord -- we want to keep it on github so that we can receive and moderate PRs, however we will be switching to a csv. Edited TODO.

**Comment by davispuh** [comment]
I think it should be possible to automate this and just pull data from all stores and automatically match it up with Steam IDs.

For reference:
* https://github.com/NikkelM/Steam-App-ID-Finder
* https://github.com/nachoaldamav/offers-tracker
* https://github.com/Sude-/lgogdownloader
* https://github.com/ValvePython/steam
* There are a lot more code out

**Comment by strycore** [comment]
I don't think its useful to maintain a database of all store IDs. It's going to be hard to maintain and cluttered. 

We can just keep the IDs of games needing a fix.

**Comment by strycore** [comment]
For the matching aspect, the lutris API can do that already.

**Comment by GloriousEggroll** [comment]
> I think it should be possible to automate this and just pull data from all stores and automatically match it up with Steam IDs.
> 
> For reference:
> 
> * https://github.com/NikkelM/Steam-App-ID-Finder
> * https://github.com/nachoaldamav/offers-tracker
> * https://github.com/Sude-/lgogdownloader
> * https://github.com/ValvePython/steam
> * There are a lot more code out

all we need to do is copy the data from our csv to our sql database, nothing more. no pulling data from other sources. the data for our database will be manually entered after reviewing and approval from our team.
