### ISSUE TITLE
TODO: create searchable web UI and API for searching the database

### ISSUE THREAD

**Issue by GloriousEggroll** [Open-Wine-Components/ULWGL-database#5]
̶-̶ ̶n̶e̶e̶d̶ ̶a̶ ̶s̶i̶m̶p̶l̶e̶ ̶w̶e̶b̶ ̶f̶r̶o̶n̶t̶ ̶e̶n̶d̶ ̶f̶o̶r̶ ̶e̶a̶s̶i̶l̶y̶ ̶s̶e̶a̶r̶c̶h̶i̶n̶g̶ ̶t̶h̶e̶ ̶d̶a̶t̶a̶b̶a̶s̶e̶ https://github.com/Open-Wine-Components/ULWGL-database/commit/1d0e0dc87ca03682d22b54a278bd05ae3dc57b0d
- need an API for application queries to the database

**Comment by strycore** [comment]
I can make that happen quickly. If you don't want to bother with a domain name and hosting, I can make it an addition to the Lutris API but it's not much more complicated to make it a completely separate database  / API.
